{
  "python_version": "3.11",
  "extra": "all",
  "test_timestamp": "2025-07-08T14:09:10.538673",
  "venv_creation": {
    "success": true
  },
  "installation": {
    "command": "C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Scripts\\pip install -e .[all] --verbose",
    "success": false,
    "returncode": 2,
    "stdout": "Using pip 23.1.2 from C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip (python 3.11)\nObtaining file:///C:/Users/andre/Pynomaly\n",
    "stderr": "ERROR: Exception:\nTraceback (most recent call last):\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 169, in exc_logging_wrapper\n    status = run_func(*args)\n             ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 248, in wrapper\n    return func(self, options, args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 377, in run\n    requirement_set = resolver.resolve(\n                      ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\resolver.py\", line 73, in resolve\n    collected = self.factory.collect_root_requirements(root_reqs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\factory.py\", line 491, in collect_root_requirements\n    req = self._make_requirement_from_install_req(\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\factory.py\", line 453, in _make_requirement_from_install_req\n    cand = self._make_candidate_from_link(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\factory.py\", line 185, in _make_candidate_from_link\n    self._editable_candidate_cache[link] = EditableCandidate(\n                                           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\candidates.py\", line 318, in __init__\n    super().__init__(\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\candidates.py\", line 156, in __init__\n    self.dist = self._prepare()\n                ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\candidates.py\", line 225, in _prepare\n    dist = self._prepare_distribution()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\candidates.py\", line 328, in _prepare_distribution\n    return self._factory.preparer.prepare_editable_requirement(self._ireq)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\operations\\prepare.py\", line 687, in prepare_editable_requirement\n    dist = _get_prepared_distribution(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\operations\\prepare.py\", line 69, in _get_prepared_distribution\n    abstract_dist.prepare_distribution_metadata(\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\distributions\\sdist.py\", line 31, in prepare_distribution_metadata\n    self.req.load_pyproject_toml()\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\req\\req_install.py\", line 484, in load_pyproject_toml\n    pyproject_toml_data = load_pyproject_toml(\n                          ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_internal\\pyproject.py\", line 64, in load_pyproject_toml\n    pp_toml = tomli.loads(f.read())\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_vendor\\tomli\\_parser.py\", line 102, in loads\n    pos = key_value_rule(src, pos, out, header, parse_float)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_vendor\\tomli\\_parser.py\", line 326, in key_value_rule\n    pos, key, value = parse_key_value_pair(src, pos, parse_float)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_vendor\\tomli\\_parser.py\", line 369, in parse_key_value_pair\n    pos, value = parse_value(src, pos, parse_float)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_vendor\\tomli\\_parser.py\", line 616, in parse_value\n    return parse_array(src, pos, parse_float)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_vendor\\tomli\\_parser.py\", line 420, in parse_array\n    pos, val = parse_value(src, pos, parse_float)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_vendor\\tomli\\_parser.py\", line 598, in parse_value\n    return parse_one_line_basic_str(src, pos)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_vendor\\tomli\\_parser.py\", line 409, in parse_one_line_basic_str\n    return parse_basic_str(src, pos, multiline=False)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Lib\\site-packages\\pip\\_vendor\\tomli\\_parser.py\", line 580, in parse_basic_str\n    raise suffixed_err(src, pos, f\"Illegal character {char!r}\")\npip._vendor.tomli.TOMLDecodeError: Illegal character '\\x00' (at line 34, column 11)\n\n[notice] A new release of pip is available: 23.1.2 -> 25.1.1\n[notice] To update, run: C:\\Users\\andre\\AppData\\Local\\Temp\\tmpkwrdm9oq\\venv_3.11_all\\Scripts\\python.exe -m pip install --upgrade pip\n",
    "warnings": [],
    "errors": [
      "ERROR: Exception:",
      "pip._vendor.tomli.TOMLDecodeError: Illegal character '\\x00' (at line 34, column 11)"
    ],
    "duration": 0.474154
  },
  "dependency_tree": {},
  "lockfile": {},
  "overall_success": false
}